### ISSUE TITLE
Error committing changes: value too long for type character varying(20)

### ISSUE THREAD

**Issue by exiledonamarginalisland** [Ghini/ghini.desktop#424] opened 2018-09-08 11:40 UTC
This error appears at times when I try to create a new accession of an existing species.

![image](https://user-images.githubusercontent.com/10896183/45253734-960bdd80-b36c-11e8-8b71-69101a6500f0.png)

I am sorry, but cannot fathom the reason, or what brings it forward. This is the trace:

(psycopg2.DataError) value too long for type character varying(20)
 [SQL: 'INSERT INTO accession (code, prov_type, wild_prov_status, date_accd, date_recvd, quantity_recvd, recvd_type, id_qual_rank, id_qual, private, species_id, intended_location_id, intended2_location_id, id, _created, _last_updated) VALUES (%(code)s, %(prov_type)s, %(wild_prov_status)s, %(date_accd)s, %(date_recvd)s, %(quantity_recvd)s, %(recvd_type)s, %(id_qual_rank)s, %(id_qual)s, %(private)s, %(species_id)s, %(intended_location_id)s, %(intended2_location_id)s, %(id)s, now(), now())'] [parameters: {'species_id': 3, 'intended2_location_id': None, 'code': u'Existing.2018.09.01.0001', 'prov_type': u'Purchase', 'id_qual_rank': None, 'private': False, 'wild_prov_status': None, 'quantity_recvd': '1', 'date_accd': datetime.date(2018, 9, 8), 'date_recvd': datetime.date(2018, 9, 1), 'id_qual': None, 'recvd_type': u'CORM', 'intended_location_id': 1, 'id': 4L}]

**Comment by mfrasca** [comment] 2018-09-08 14:24
Existing.2018.09.01.0001
duplicate of #399 
[work on it is already planned](https://github.com/Ghini/ghini.desktop/milestone/6)

**Closed as completed by mfrasca** 2018-09-08 14:24 UTC
Labels: duplicate
